name: biowayapp
description: "BioWay - Aplicación de reciclaje"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  google_maps_flutter: ^2.5.3
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0
  barcode_scan2: ^4.3.0
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  intl: ^0.19.0
  firebase_messaging: ^14.7.20
  # Reemplazamos flutter_local_notifications por awesome_notifications
  awesome_notifications: ^0.9.2
  http: ^1.3.0
  xml: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/cp_data.json

  fonts:
    - family: Hammersmith_One
      fonts:
        - asset: assets/fonts/HammersmithOne-Regular.ttf